### ISSUE TITLE
Fix the issue `Mac libdb2.dylib image not found` rather than provide a workaround

### ISSUE THREAD

**Issue by snowch** [ibmdb/python-ibmdb#276]
It seems we only have a workaround for this issue - https://github.com/ibmdb/python-ibmdb/issues/187

Can this issue be fixed by doing some extra setup in the installation script?

The documented workaround didn't work for me.  My error:

```
Traceback (most recent call last):
  File "./index.py", line 3, in <module>
    import ibm_db
ImportError: dlopen(/Users/snowch/Library/Python/2.7/lib/python/site-packages/ibm_db.so, 2): Library not loaded: libdb2.dylib
  Referenced from: /Users/snowch/Library/Python/2.7/lib/python/site-packages/ibm_db.so
  Reason: image not found
```
It seems the file names have changes.  My workaround:

```
$ install_name_tool -change libdb2.dylib /Users/snowch/Library/Python/2.7/lib/python/site-packages/clidriver/lib/libdb2.dylib ibm_db.so
```

**Comment by rjkuro** [comment]
This is great. The command worked fine and resolved the error on my environment. 

It seems Apple is changing the policy for DYLD_LIBRARY_PATH and the work-around using it didn't work for me. (I use macOS Sierra). This fix should be integrated into the build or deployment so that each developer doesn't need to issue the command.

**Comment by SabaKauser** [comment]
we have documented workaround here -> https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/ibm_db_on_MAC_OS_Hints_and_Tips?lang=en

**Comment by thecyman** [comment]
I believe we should re-open this ticket. In the most up-to-date MacOS version, the driver should work with a basic install: `pip install ibm_db` without further workarounds.

**Comment by germanattanasio** [comment]
I agree with @thecyman if someone has an idea on how to set the environment variable I can try to get a PR for this.

**Comment by charleybeller** [comment]
@germanattanasio 
I was running into problem 2 in the documented workaround. I didn't need to change environment variables or run install_name_tool, I only needed to add a missing simlink 
from the site-packages/ subdirectory:
`ln -s clidriver/lib/libdb2.dylib libdb2.dylib`

I found this as part of the solution documented in this comment:
https://github.com/ibmdb/python-ibmdb/issues/187#issuecomment-310765420

**Comment by fe01134** [comment]
I hit this on mac os and the work around here did work https://github.com/ibmdb/python-ibmdb/tree/master/IBM_DB/ibm_db

**BUT** I don't have to set Environment variables for other python modules I use. It would be really helpful if the IBM DB2 team could make their python modules work like others industry Python modules.

**Comment by SabaKauser** [comment]
This is fixed and will be available in next release shortly.

**Comment by surace997** [comment]
1. Traceback (most recent call last):
  File "/Users/sureshdangol/Desktop/CSI 127(PYTHON)/daily attentence/daily att.py", line 6, in <module>
    name= input('Please enter name of input file: ')
  File "<string>", line 1, in <module>
NameError: name 'dailyattendences' is not defined

2. Traceback (most recent call last):
  File "/Users/sureshdangol/Desktop/CSI 127(PYTHON)/binary to decimal.py", line 5, in <module>
    for c in binString:
TypeError: 'int' object is not iterable

what would be the solution for these problems.

**Comment by sebastiangold** [comment]
I am still experiencing this issue, even after following the troubleshooting, except for disabling the security on my mac. None of it seemed to fix it, although the command itself ran successfully.
link: https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/ibm_db_on_MAC_OS_Hints_and_Tips?lang=en

**Comment by carlosibm** [comment]
Me too.    I hit this again after upgrading to a new Mac.   Here is the workaround again.  What a pain.

**Issues with MAC OS X**
If you run into errors for libdb2.dylib as below:
```
>>> import ibm_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.5/site-packages/ibm_db.cpython-35m-darwin.so, 2): Library not loaded: libdb2.dylib
  Referenced from: /usr/local/lib/python3.5/site-packages/ibm_db.cpython-35m-darwin.so
  Reason: image not found

```
You would need to set DYLD_LIBRARY_PATH to point to lib folder as per the installation location of clidriver in your environment. Assuming the driver is installed at /usr/local/lib/python3.5/site-packages/clidriver, you can set the path as:

`export DYLD_LIBRARY_PATH=/usr/local/lib/python3.5/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH
`

**Comment by CelikDuygu** [comment]
@carlosibm  This fixed my problem! Thank you.
