### ISSUE TITLE
ibm_db on MacOS Monterey Beta causes C malloc crash

### ISSUE THREAD

**Issue by edumorlom** [ibmdb/python-ibmdb#648]
Running the following method on MacOS Monterey:

```conn = ibm_db.connect(db_host, "", "")```

will cause ANY Python version to crash with the following error:
```
Python(35879,0x1101f6600) malloc: *** error for object 0x7ffb5ea1a120: pointer being freed was not allocated
Python(35879,0x1101f6600) malloc: *** set a breakpoint in malloc_error_break to debug
```

This is specific to macOS Monterey, the issue only started happening when upgrading my OS.

I have tested on Python 3.8, 3.9, and 3.10 beta.
Currently the latest: ` ibm-db~=3.0.4`.

**Comment by amukherjee28** [comment]
Hi @edumorlom 

From what you are trying to say here is this is OS specific issue after the version upgrade in MAC. Currently we have tested till 10.15 catalina.

This needs to be investigated in case there are some breaking changes in the new releases of MAC OS.

Also currently we are supporting till python 3.9.
We will investigate the new version release and come back on this.

I understand that you confirm before the upgrade thing were working fine.

**Comment by edumorlom** [comment]
Yes, I confirm everything was working fine before upgrading. The issue happens with all versions of Python running on the latest MacOS Beta.

Python 3.6 also causes the issue.

**Comment by amukherjee28** [comment]
Hi @edumorlom 

This is beyond current supported OS version. We have not yet certified the current release in question.
However could you confirm if you are using the clidriver downloaded with respect with the ibm_db driver installation or are you using some other version of clidriver and setting the PATH of the driver using IBM_DB_HOME environment variable.
Please let me know the details of the inline clidriver used in this case.

Thanks

**Comment by edumorlom** [comment]
Hello, all I am doing is `pip install ibm_db`. I am not installing anything else.

**Comment by amukherjee28** [comment]
Looks like we have to test it in the version of OS in question. We have not yet acquired the new MAC version that was reported for this issue. So I have to put this on hold till we test it in the current version and check if there are any breaking changes.

I will continue to check if any workaround could be found.

Thanks

**Comment by edumorlom** [comment]
Awesome, thank you! Just wanted to ensure you guys are aware of the issue since the new macOS release is imminent.

**Comment by amukherjee28** [comment]
Yes we will work on this and keep the issue open till we have a solution.

Thanks.

**Comment by edumorlom** [comment]
I am also available in IBM to test. I continue to see this issue on the stable version of Monterey on version 3.1.0.

**Comment by jamsden** [comment]
I'm using ibm_db for monthly customer reports that now fail. A prompt fix would be most appreciated. These reports are against DB2 11.1.9.0 if that matters.

**Comment by jamsden** [comment]
Further information: dbeaver Version 21.2.3.202110151816 on macOS 12.0.1 does work connecting to the same database, but using TLS, not GSKit. 

Does that suggest any workaround?

**Comment by amukherjee28** [comment]
I had a discussion with @davidg42 the other day and did some investigation on the same.

Can we ask the users to find the clidriver path and then set the DYLD_LIBRARY_PATH environment variable to <clidriver/lib> path.

So I would ask @jamsden @edumorlom 
Can you set the path
export DYLD_LIBRARY_PATH=<clidriver_PATH>/lib:$DYLD_LIBRARY_PATH
and then try running the application.

In case you want to find where the clidriver is installed you can run pip3 --version command to find the site-packages folder and the clidriver would be inside the site-packages folder.

**Comment by jamsden** [comment]
Using v11.1.4fp6_macos_dsdriver.dmg and:
```
export DYLD_LIBRARY_PATH=/Applications/dsdriver/lib:$DYLD_LIBRARY_PATH
```
did indeed fix the problem for me.

**Comment by edumorlom** [comment]
Using:
`export DYLD_LIBRARY_PATH=/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/clidriver/lib:$DYLD_LIBRARY_PATH`

fixed the issue for me

**Comment by bimalkjha** [comment]
@edumorlom Good to see [this comment](https://github.com/ibmdb/node-ibm_db/issues/801#issuecomment-959641837) too. Deleting/renaming `/usr/local/Caskroom/miniconda/base/lib/python3.8/site-packages/clidriver/lib/libstdc++.6.dylib` should also fix the issue. 
Seems Monterey comes with updated version of g++ and libstdc++ which is not compatible with the clidriver/lib/libstdc++.6.dylib`. Thanks.

**Comment by Keyyi** [comment]
Hi all,
I am having trouble with `conn = ibm_db.connect(db_host, "", "")` as well. I have tried both methods above and they are not working for me. 
Setting the DYLD_LIBRARY_PATH environment variable still cause:
```
python3(35835,0x110037600) malloc: *** error for object 0x7ffb46d5ae00: pointer being freed was not allocated
python3(35835,0x110037600) malloc: *** set a breakpoint in malloc_error_break to debug
```
Removing the file will cause error when running `import ibm_db_dbi as db`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/name/.pyenv/versions/3.8.12/lib/python3.8/site-packages/ibm_db_dbi.py", line 45, in <module>
    import ibm_db
ImportError: dlopen(/Users/name/.pyenv/versions/3.8.12/lib/python3.8/site-packages/ibm_db.cpython-38-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Users/name/.pyenv/versions/3.8.12/lib/python3.8/site-packages/clidriver/lib/libdb2.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
```
What might be the issue here and Is there anything else I can do with this? Thanks!

**Comment by bimalkjha** [comment]
@Keyyi Install latest version of gcc and g++ in your system which should install latest version of libstdc++ library. Thanks.

**Comment by bimalkjha** [comment]
Removed libstdc++.6.dylib from clidriver/lib. So, for new installation, this issue should be fixed now.
If post installation, ibm_db complains about libstdc++.6.dylib on any system, install the latest version of gcc and g++ compilers. Thanks.

**Comment by marcothinnes** [comment]
The issue still exists for me under Mac Ventura 13.x, Python 3.11

**Comment by bimalkjha** [comment]
@marcothinnes You need to install gcc8 using brew. Check [this comment](https://github.com/ibmdb/python-ibmdb/issues/748#issuecomment-1117627801) for details. Thanks.

**Comment by marcothinnes** [comment]
@bimalkjha Thank you! After installing gcc the error still exists.

**Comment by bimalkjha** [comment]
Bimal Jha [12:39 AM]
export DYLD_LIBRARY_PATH=/usr/local/lib/gcc/8:/Users/marcostaschik/.local/share/virtualenvs/edeka-process-mining-backend-jpQtl6Ek/lib/python3.11/site-packages/clidriver/lib
[12:39] run above command and then try


Marco Thinnes [12:53 AM] yes this works. Thanks, but I need to apply this everytime I start the shell now.
[12:53] Thank you very much
