### ISSUE TITLE
ibm_db Python library not working on MacOS Monterey

### ISSUE THREAD

**Issue by shawn-gang** [ibmdb/python-ibmdb#743]
Followup on the previous issue: https://github.com/ibmdb/python-ibmdb/issues/648

Environment
python3 version 3.8.9
ibm_db version 3.1.1 (latest, which supposedly has the fix as listed in the issue)
macos Monterey (12.3.1) and xcode.

Workflow/reproduce:
```
sudo pip3 uninstall ibm_db
sudo pip3 install ibm_db (=> Successfully installed ibm-db-3.1.1)

sudo python3 {python script that uses ibm_db}
=> I get the same malloc issue from https://github.com/ibmdb/python-ibmdb/issues/648
```

Rename clidriver\lib\libstdc++.6.dylib
```
pwd (=> /Library/Python/3.8/site-packages/clidriver/lib). This directory contains the file 'libstdc++.6.dylib'
sudo mv libstdc++.6.dylib renamingTHIS
...

sudo python3 {python script that uses ibm_db}
ImportError: dlopen(/Library/Python/3.8/site-packages/ibm_db.cpython-38-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Library/Python/3.8/site-packages/clidriver/lib/libdb2.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
```
/usr/lib/ is a system protected directory. I can't modify it even after prefixing commands with `sudo`.

My DYLD_LIBRARY_PATH variable:
```
echo $DYLD_LIBRARY_PATH
/Library/Python/3.8/site-packages/clidriver/lib:
```

**Comment by amukherjee28** [comment]
@shawn-gang 

The library loading mechanism in MAC is now expected to work in such a way that ibm_db dependent libraries are supposed to be loaded from clidriver/lib folder.
Setting DYLD_LIBRARY_PATH is optional as all required libraries are loaded from the same location.

If you check the library dependency of the libraries in clidriver/lib folder using the command ```otool -L libdb2.dylib``` command following is the output

```
libdb2.dylib:
        libdb2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1677.104.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 1.0.0)
        @loader_path/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.25.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.100.1)
        /usr/local/lib/gcc/8/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

From the above output if you see the expected location of loading of libstdc++.6.dylib is @loader_path which is the site-packages/clidriver/lib location.

Renaming the library in that location will not help and you will end up having the loading error
```
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ibm_db.cpython-39-darwin.so, 0x0002): Symbol not found: ___cxa_throw_bad_array_new_length
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/clidriver/lib/libdb2.dylib
  Expected in: /usr/lib/libstdc++.6.dylib
```

The library should NOT be renamed in the clidriver/lib location as the new clidriver which is the fix for MAC OS monterey is expected to load the library from the location.

Now coming to the second case where you have a duplicate library in the /usr/lib location this contradicts the loading logic and you end up getting the error
```
Python(35879,0x1101f6600) malloc: *** error for object 0x7ffb5ea1a120: pointer being freed was not allocated
Python(35879,0x1101f6600) malloc: *** set a breakpoint in malloc_error_break to debug
```

The solution to avoid this error is to rename the library in the /usr/lib location where the duplicate is found.

**Comment by shawn-gang** [comment]
hi @amukherjee28, does this mean the only fix is to rename the library within the `/usr/lib` directory? That directory is considered protected, I am unable to make any write changes to it even with `sudo`. It seems the only way to make changes there is to disable System Integrity Protection temporarily, which I am hesitant to do.

```
sudo mv libstdc++.6.dylib renameTHIS
mv: rename libstdc++.6.dylib to renameTHIS: Operation not permitted
```

**Comment by bimalkjha** [comment]
@shawn-gang Please share output of commands: `ls -l /usr/lib/libstd*` and `xcode-select -v`. Thanks.

**Comment by bimalkjha** [comment]
@shawn-gang Copy `clidriver/lib/libstdc++.6.dylib` as `/usr/lib/libstdc++.6.dylib` or `/usr/lib/libstdc++.6.0.9dylib` and then verify. thanks.

**Comment by shawn-gang** [comment]
After meeting with support:
- got the library to work with Python 2.7
  - solution: install gcc through brew and set the environment variable IBM_DB_HOME to `{whatever}/node_modules/ibm_db/installer/clidriver`. This requires Node.js and doing `npm install ibm_db` prior
  - not feasible unfortunately as Python 2.7 is out of support

Still an open issue with Python 3.

**Comment by ajaykg68** [comment]
@shawn-gang Hi Shawn, Have you tried the workaround with Python 3?

**Comment by shawn-gang** [comment]
Hi @ajaykg68, the workaround does not work with Python 3.

**Comment by bimalkjha** [comment]
@shawn-gang `npm install ibm_db` and setting IBM_DB_HOME is not required for Python2.7. After installation of gcc compiler, it normal installation should also work. npm install and setting env var was the process of our problem diagnosis. 
Lets connect via webex again to look into system and make ibm_db working using python3. Thanks.

**Comment by amukherjee28** [comment]
@shawn-gang From the last webex session we have seen that the issue is infact with the library libstdc++.

The problem is with the new version of mac the library libstdc++.so.6 from /usr/lib has been removed and only the soft link remains. This causes the issue of library being loaded at run time when used by ibm_db.

As a resolution the clidriver/lib folder is shipped with the library but in some cases even then the loading of the library fails.

One solution to this is to download the clidriver separately (like in the webex we used the clidriver form the node ibm_db installation) and set the same location in the IBM_DB_HOME environment variable.

Once the above is set install ibm_db (```pip install ibm_db or pip3 install ibm_db```).

This will skip downloading the clidriver during installation.

Also set the environment variable DYLD_LIBRARY_PATH = <clidirver path>/lib

With the above the dependency should be resolved. 
As we saw in the webex call for python2 this approach worked the same should also work for python3 as well.

**Comment by bimalkjha** [comment]
@shawn-gang Install latest version of XCode from `App Store`, restart your system and then verify. Thanks.

**Comment by harshit-sh** [comment]
@bimalkjha I too am facing the same issue and installing XCode (and restarting) didn't help. I am using Python 3.9.7 with latest `ibm_db` package 3.1.1

**Comment by ikhnaton** [comment]
@bimalkjha Has there been any progress on this issue?  This has been an issue for over a month now and your suggested solution doesn't work for those of us with IBM owned machines.

**Comment by bimalkjha** [comment]
@ikhnaton This issue is specific to IBM Macbook which has specific restrictions. No other user is facing this issue now and we are unable to reproduce it in our Mac systems with similar config.
Please provide access to a dedicated system where we can login remotely using my ibmid `Bimal.Jha1@ibm.com` and work for 4-5 hours for few days until we make ibm_db working on these systems. We need sudo access too. We found that even sudo is unable to do any permission change under /usr/lib dir which is not good.
From the investigation so far we suspect some gcc library is not accessible by libstd at runtime using python3. Similar issue was for python2 also that we resolved by installing the gcc8 and changing directory permission. We need some dedicated time to look into system to find which permissions are needed for IBM Macbook so that we can document the requirements. Thanks.

**Comment by bimalkjha** [comment]
Same issue reported by other user which is fixed now: https://github.com/ibmdb/python-ibmdb/issues/748

**Comment by bimalkjha** [comment]
@ikhnaton Similar issue was faced by another IBMer matheus.rangel@ibm.com and it is now fixed for him. Could you please check with him. Thanks.

**Comment by shawn-gang** [comment]
hi @bimalkjha, I verified that the file ` /usr/local/lib/gcc/8/libgcc_s.1.dylib` exists on my system but it's still not working for me

**Comment by bimalkjha** [comment]
This issue has been closed because the Parent Case ( TS009227350 ) was closed. Thanks.
